// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members 
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfSfr3VcmMMm2yc2Xo80m5fW5EUHgmmw',
    appId: '1:827229036452:web:9d13205ac0f4d14c2c6b31',
    messagingSenderId: '827229036452',
    projectId: 'buscardapp-af050',
    authDomain: 'buscardapp-af050.firebaseapp.com',
    storageBucket: 'buscardapp-af050.appspot.com',
    measurementId: 'G-4VWPC9YQV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLb2FglO_dn0czOFenGYOuYHb2G9zH_o',
    appId: '1:827229036452:android:7fa14eb7e73eca9e2c6b31',
    messagingSenderId: '827229036452',
    projectId: 'buscardapp-af050',
    storageBucket: 'buscardapp-af050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgT0YiNO1azPG5T7SSGN5zTTM9aA90GUs',
    appId: '1:827229036452:ios:38c77a6f614319b12c6b31',
    messagingSenderId: '827229036452',
    projectId: 'buscardapp-af050',
    storageBucket: 'buscardapp-af050.appspot.com',
    iosClientId: '827229036452-p0hto1jm1m51gv0krnr8no7tfo7snhrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgT0YiNO1azPG5T7SSGN5zTTM9aA90GUs',
    appId: '1:827229036452:ios:38c77a6f614319b12c6b31',
    messagingSenderId: '827229036452',
    projectId: 'buscardapp-af050',
    storageBucket: 'buscardapp-af050.appspot.com',
    iosClientId: '827229036452-p0hto1jm1m51gv0krnr8no7tfo7snhrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardapp',
  );
}
